# Generated by Django 3.0.5 on 2025-04-22 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0009_course_qualification'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='negative_marking',
            field=models.BooleanField(default=False),
        ),
    ]
