# Generated by Django 3.0.5 on 2025-05-12 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0010_course_negative_marking'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='negative_marking_percentage',
            field=models.PositiveIntegerField(default=50, help_text='Negative marking in percentage'),
        ),
        migrations.AddField(
            model_name='course',
            name='test_duration',
            field=models.PositiveIntegerField(default=30, help_text='Test duration in minutes'),
        ),
    ]
