# Generated by Django 3.0.5 on 2025-04-22 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_remove_student_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='qualification',
            field=models.CharField(choices=[('10th', '10th Standard'), ('11th', '11th Standard'), ('12th', '12th Standard'), ('bsc_1st_year', 'B.Sc. - 1st Year'), ('bsc_2nd_year', 'B.Sc. - 2nd Year'), ('bsc_3rd_year', 'B.Sc. - 3rd Year'), ('bca_1st_year', 'BCA - 1st Year'), ('bca_2nd_year', 'BCA - 2nd Year'), ('bca_3rd_year', 'BCA - 3rd Year'), ('bcom_1st_year', 'B.Com. - 1st Year'), ('bcom_2nd_year', 'B.Com. - 2nd Year'), ('bcom_3rd_year', 'B.Com. - 3rd Year'), ('ba_1st_year', 'B.A. - 1st Year'), ('ba_2nd_year', 'B.A. - 2nd Year'), ('ba_3rd_year', 'B.A. - 3rd Year'), ('mba', 'MBA'), ('mca', 'MCA'), ('msc', 'M.Sc.'), ('ma', 'M.A.'), ('mcom', 'M.Com.'), ('diploma', 'Diploma'), ('phd', 'Ph.D.'), ('other', 'Other')], default='10th', max_length=50),
        ),
    ]
